#!/usr/bin/env bash
fileToPreview=$1

if [[ -z ${fileToPreview} ]] ; then
  echo "Please specify tex file to preview"
  exit 1
fi

# Input can be either pdf or tex and this'll sort it out
name=${fileToPreview%.*}
texFile=${name}.tex
pdfFile=${name}.pdf

sourceFiles="${name}.tex"
for ext in sty cls ; do
  [[ -f "${name}.${ext}" ]] && sourceFiles="$sourceFiles ${name}.${ext}"
done
echo "Source files : $sourceFiles"

echo "Previewing $texFile"
make --always-make "$pdfFile"

fswatch -o ${sourceFiles} | xargs -n1 -I{} make --always-make "$pdfFile"
